@url = http://localhost:5000
@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}/

###
GET {{url}}/reservations

> {%
    const d = new Date();
    const yyyy = d.getFullYear();
    const mm = String(d.getMonth() + 1).padStart(2,'0');
    const dd = String(d.getDate()).padStart(2,'0');
    client.global.set("today", `${yyyy}-${mm}-${dd}`);

    if (Array.isArray(response.body) && response.body.length > 0) {
        client.global.set(
            "reservationId",
            response.body[0].id
        );
    } else {
        client.global.clear("reservationId");
    }
%}

###
GET {{url}}/reservations/{{reservationId}}

###
POST {{url}}/reservations
Content-Type: application/json

{
  "employeeName": "Wojciech Gargas",
  "ParkingSpotId": "{{parkingSpotId}}",
  "licensePlate": "XY12345",
  "date": "{{today}}"
}

###
POST {{url}}/reservations
Content-Type: application/json

{
  "employeeName": "Wojciech Gargas",
  "ParkingSpotId": "{{parkingSpotId}}",
  "licensePlate": "XY12345",
  "date": "2022-01-01"
}

###
PUT {{url}}/reservations
Content-Type: application/json

{
  "reservationId": "{{reservationId}}",
  "licensePlate": "XY00000"
}

###
DELETE {{url}}/reservations
Content-Type: application/json

{
  "reservationId": "{{reservationId}}"
}
