@url = http://localhost:5000
@parkingSpotId = 00000000-0000-0000-0000-000000000001

###
GET {{url}}/reservations

> {%
    client.global.set(
        "reservationId",
        response.body[0].id
    );
%}

###
GET {{url}}/reservations/{{reservationId}}

###
POST {{url}}/reservations
Content-Type: application/json

{
  "employeeName": "Wojciech Gargas",
  "ParkingSpotId": "{{parkingSpotId}}",
  "licensePlate": "XY12345",
  "date": "2026-02-04"
}

###
PUT {{url}}/reservations
Content-Type: application/json

{
  "reservationId": "{{reservationId}}",
  "licensePlate": "XY00000"
}

###
DELETE {{url}}/reservations
Content-Type: application/json

{
  "reservationId": "{{reservationId}}"
}
